version: 2

sources:
  - name: gz_raw_data
    tables:
      - name: raw_gz_sales
        description: sales of Greenweez / we have one row per product_id found in each orders_id
        freshness:
          warn_after: {count: 90, period: day}
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: id of the order
          - name: pdt_id
            description: id of the product
          - name: revenue
            description: income
          - name: quantity
            description: number of products sold
      - name: raw_gz_product
        description: products of Greenweez / we have on row per product_id and its purchase price
        tests:
         - unique:
            column_name: products_id
        columns:
          - name: products_id
            tests:
              - not_null
            description: represents each product
          - name: purchse_price
            description: cost of that product
      - name: raw_gz_ship
        description: ships of Greenweez / we have on row per order_id and its shipping costs
        tests:
         - unique:
            column_name: orders_id
        columns:
          - name: orders_id
            tests:
                - not_null
            description: id of the order
          - name: shipping_fee
            description: cost a customer pays to have an item delivered
          - name: logcost
            description: cost associated with logging operations
          - name: ship_cost
            description: cost associated with product shipping
      - name: adwords
        identifier: raw_gz_adwords
        description: adwords advertising campaign
        columns:
          - name: date_date
            tests:
                - unique
                - not_null
            description: date
          - name: paid_source
            description: source of advertising
          - name: campaign_key
            description: id of the campaign
          - name: camPGN_name
            description: name of the campaign
          - name: ads_cost
            description: cost of the add
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks
      - name: bing
        identifier: raw_gz_bing
        description: bing advertising campaign
        columns:
          - name: date_date
            tests:
                - unique
                - not_null
            description: date
          - name: paid_source
            description: source of advertising
          - name: campaign_key
            description: id of the campaign
          - name: camPGN_name
            description: name of the campaign
          - name: ads_cost
            description: cost of the add
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks
      - name: criteo
        identifier: raw_gz_criteo
        description: criteo advertising campaign
        columns:
          - name: date_date
            tests:
                - unique
                - not_null
            description: date
          - name: paid_source
            description: source of advertising
          - name: campaign_key
            description: id of the campaign
          - name: camPGN_name
            description: name of the campaign
          - name: ads_cost
            description: cost of the add
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks
      - name: facebook
        identifier: raw_gz_facebook
        description: facebook advertising campaign
        columns:
          - name: date_date
            tests:
                - unique
                - not_null
            description: date
          - name: paid_source
            description: source of advertising
          - name: campaign_key
            description: id of the campaign
          - name: camPGN_name
            description: name of the campaign
          - name: ads_cost
            description: cost of the add
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks
            
          

models:
  - name: int_sales_margin
    description: join raw_gz_sales and raw_gz_product + purchase_cost and margin
    columns:
      - name: products_id
        description: represents each product
        tests:
          - not_null
      - name: orders_id
        description: id of the order
        tests:
          - not_null
      - name: date_date
        description: date
        tests:
          - not_null
      - name: revenue
        description: income
        tests:
          - not_null
      - name: quantity
        description: quantity of products sold
        tests:
          - not_null
      - name: purchase_cost
        description: quantity * purchase_price
        tests:
          - not_null
      - name: margin
        description: revenue - (quantity * purchase_price)
        tests:
          - not_null
  - name: int_orders_margin
    description: sales_margin grouped by orders_id and date_date
    columns:
      - name: orders_id
        description: id of the order
        tests:
          - unique
          - not_null
      - name: date_date
        description: date
        tests: 
          - not_null
      - name: revenue
        description: sum income
        tests:
          - not_null
      - name: quantity
        description: sum quantity of products sold
        tests:
          - not_null
      - name: purchase_cost
        description: sum purchase_cost
        tests:
          - not_null
      - name: margin
        description: sum margin
        tests:
          - not_null
  - name: int_orders_operational
    description: join between int_orders_margin and raw_gz_ship adn operational_margin calculation
    columns:
      - name: orders_id
        description: id of the order
        tests:
          - unique
          - not_null
      - name: date_date
        description: date
        tests: 
          - not_null
      - name: operational_margin
        description: margin + shipping_fee - logcost - ship_cost
        tests:
          - not_null
      - name: quantity
        description: quantity of products sold
        tests:
          - not_null
      - name: revenue
        description: income
        tests:
          - not_null
      - name: purchase_cost
        description: purchase_cost
        tests:
          - not_null
      - name: margin
        description:  margin
        tests:
          - not_null
      - name: shipping_fee
        description: paid by the customer
        tests:
          - not_null
      - name: logcost
        description: paid by the company
        tests:
          - not_null
  
  - name: int_campaigns
    description: unification of all campaigns tables (facebook, criteo, bing, adwords)
    columns:
      - name: date_date
        tests:
            - unique
            - not_null
        description: date
      - name: paid_source
        description: source of advertising
      - name: campaign_key
        description: id of the campaign
      - name: campaign_name
        description: name of the campaign
      - name: ads_cost
        description: cost of the add
      - name: impression
        description: number of impressions
      - name: click
        description: number of clicks

  - name: int_campaigns_days
    description: int_campaigns by day
    columns:
      - name: date
        tests:
            - unique
            - not_null
        description: date
      - name: nb_paid_source
        description: number of advertising sources
      - name: nb_campaign_key
        description: number of campaign ids
      - name: nb_campaign_name
        description: number of campaign names
      - name: ads_cost
        description: cost of the add
      - name: impression
        description: number of impressions
      - name: click
        description: number of clicks

  - name: finance_days
    description: mart model grouped by day for stakeholders
    columns:
      - name: date
        tests:
              - unique
              - not_null
        description: date
      - name: nb_transactions
        description: number of transactions for that day 
      - name: revenue
        description: income
      - name: avg_basket
        description: avg revenue per day
      - name: operational_margin
        description: margin + shipping_fee - logcost - ship_cost
      - name: purchase_cost
        description: purchase_cost
      - name: shipping_fee
        description:  paid by the customer
      - name: log_cost
        description: paid by the customer
      - name: nb_prod_sold
        description: number of products sold that day
  - name: finance_campaigns_day
    description: join between int_campaigns_day and finance_days to calculate ads_margin
    columns:
      - name: date
        tests:
              - unique
              - not_null
        description: date
      - name: ads_margin
        description: number of transactions for that day 
      - name: avg_basket
        description: avg revenue per day
      - name: operational_margin
        description: margin + shipping_fee - logcost - ship_cost
      - name: ads_cost
        description: cost of advertisment
      - name: ads_impression
        description: number of impressions
      - name: ads_clicks
        description:  number of clicks
      - name: nb_prod_sold
        description: number of products sold that day
      - name: revenue
        description: income
      - name: purchase_cost
        description: cost of product purchase
      - name: shipping_fee
        description: cost of shipping paid by the client
      - name: log_cost
        description: cost of logistics
      - name: ship_cost
        description: cost of shipping