version: 2

sources:
  - name: gz_raw_data
    tables:
      - name: raw_gz_sales
        description: sales of Greenweez / we have one row per product_id found in each orders_id
        tests:
         - dbt_utils.unique_combination_of_columns:
             combination_of_columns:
                 - pdt_id
                 - date_date
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: id of the order
          - name: pdt_id
            description: id of the product
          - name: revenue
            description: income
          - name: quantity
            description: number of products sold
      - name: raw_gz_product
        description: products of Greenweez / we have on row per product_id and its purchase price
        tests:
         - unique:
            column_name: products_id
        columns:
          - name: products_id
            tests:
              - not_null
            description: represents each product
          - name: purchse_price
            description: cost of that product
      - name: raw_gz_ship
        description: ships of Greenweez / we have on row per order_id and its shipping costs
        tests:
         - unique:
            column_name: orders_id
        columns:
          - name: orders_id
            tests:
                - not_null
            description: id of the order
          - name: shipping_fee
            description: cost a customer pays to have an item delivered
          - name: logcost
            description: cost associated with logging operations
          - name: ship_cost
            description: cost associated with product shipping